config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root           'staticpages#home'
  get 'about' => 'staticpages#about'
  get 'account' => 'users#show'
  get 'resumesmath' => 'resumes#resumesmath'
  get 'resumesarts' => 'resumes#resumesarts'
  get 'resumesengineering' => 'resumes#resumesengineering'

  resources :resumes

end

app/models/resume.rb
class Resume < ActiveRecord::Base
	belongs_to :user
	#list of companies that this resume received interview from
	#list of faculties and majors
	acts_as_taggable_on :companies, :majors
	validates :user_id, presence: true
	validates :resume, presence: true
	has_attached_file :resume,
		:bucket => ENV["bucket"],
	  :s3_credentials => {
	    :access_key_id => ENV["AWS_ACCESS_KEY_ID"],
	    :secret_access_key => ENV["AWS_SECRET_ACCESS_KEY"]
	  },
		:processors => [:pdfprocessor],
		:styles => {
			:fullsize => ["50x50",:jpg],
			:small => ["50x50",:jpg]
		},
		:convert_options => {:fullsize => '-quality 90'}
	validates_attachment_content_type :resume, :content_type => %w(application/pdf)

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :resumes
	validates :name, presence: true
	validates :faculty, presence: true
	validates :first_major, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
  helper_method :resource, :resource_name, :devise_mapping

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:sign_up) << :faculty
    devise_parameter_sanitizer.for(:sign_up) << :first_major
    devise_parameter_sanitizer.for(:sign_up) << :second_major
  end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
	include ResumesHelper

	def index
		@resumes = Resume.all
	end
	def new
		@resume = Resume.new
	end
	def create
		@resume = Resume.new(resume_params)

		@resume.major_list.add(current_user.first_major)
		if current_user.second_major != nil
			@resume.major_list.add(current_user.second_major)
		end

		if @resume.save
			#flash[:success] = "Resume created"      doesn't work, i want it to though
			@resume.url = get_image_url(@resume.id, @resume.resume_file_name)
			redirect_to '/account'

		else
			render 'new'
		end
	end
	def show
		if user_signed_in?
			@resume=Resume.find(params[:id])
		else
			redirect_to '/users/sign_in'
		end
	end
	def destroy
		Resume.find(params[:id]).destroy
		redirect_to :back
	end
	def update
	end
	def edit

		if current_user.id == Resume.find(params[:id]).user_id
			@resume = Resume.find(params[:id])
		else
			redirect_to '/users/sign_in'
		end
	end
	def resumesarts
		@resumes = Resume.all
	end
	def resumesmath
		@resumes = Resume.all
	end
	def resumesengineering
		@resumes = Resume.all
	end
	private
		def resume_params
			params.require(:resume).permit(:url, :user_id, :resume, :resume_file_name, :faculty)
		end
end

app/controllers/staticpages_controller.rb
#controller which handles all the static pages

class StaticpagesController < ApplicationController

	#home page
	def home
		@resumes = Resume.take(3)
	end



end

app/controllers/users/registrations_controller.rb
# controllers/users/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  before_filter :configure_permitted_parameters

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:name, :faculty, :first_major)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  	@user=User.find(current_user.id)
  	@resumes = Resume.all
  end
  def new
		@user = User.new
	end
  def create
		User.new(user_params)

	end
  private
		def user_params
			params.require(:user).permit(:name, :faculty, :first_major)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
	def get_image_url(id,filename)
		@s3 = AWS::S3.new(
			:access_key_id => ENV['AWS_ACCESS_KEY_ID'],
			:secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
		)

		key = 'resumes/resumes/000/000/'+ "%03d" % id+  '/fullsize/'+filename[0..-4]+"jpg"
		object = @s3.buckets[ENV['AWS_BUCKET']].objects[key]
		@image_url = object.public_url().to_s;
		#@image_url = object.url_for(:get).to_s;
		return @image_url
	end

	def get_thumbnail_url(id,filename)
		@s3 = AWS::S3.new(
			:access_key_id => ENV['AWS_ACCESS_KEY_ID'],
			:secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
		)
		object = @s3.buckets[ENV['AWS_BUCKET']].objects['resumes/resumes/000/000/'+ "%03d" % id+ '/thumbnail/'+filename[0..-4]+"jpg"]
		@image_url = object.url_for(:get, {:expires => 30.minutes.from_now, :secure => true}).to_s;
		return @image_url
	end
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<!-- ******HEADER****** -->
<header id="header" class="header">
    <div class="container">
        <h1 class="logo pull-left">
            <a href="/">
                <span class="logo-title">ResumeBox</span>
            </a>
        </h1><!--//logo-->
        <nav id="main-nav" class="main-nav navbar-right" role="navigation">
            <div class="navbar-header">
                <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button><!--//nav-toggle-->
            </div><!--//navbar-header-->
            <div class="navbar-collapse collapse" id="navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active nav-item sr-only"><a class="scrollto" href="">Home</a></li>


                    <% if user_signed_in? %>
                        <li class="nav-item"><%= link_to "All Resumes", resumes_path %></li>
                        <li class="nav-item"><%= link_to "My Account", account_path %></li>
                        <li class="nav-item"><%= link_to "Logout", destroy_user_session_path, :method => :delete%></li>
                    <% else %>
                        <li class="nav-item"><a class="scrollto" href="#features">Features</a></li>
                        <li class="nav-item"><a class="scrollto" href="#docs">Docs</a></li>
                    <% end %>
                </ul><!--//nav-->
            </div><!--//navabr-collapse-->
        </nav><!--//main-nav-->
    </div>
</header><!--//header-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ResumeBox</title>
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="favicon.ico">
    <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= yield %>


</body>
</html>

app/views/resumes/edit.html.erb
<%= render 'layouts/navbar' %>
<section id="resume" class="resume section offset-header">
    <div class = "container text-center">
        <h2>Edit your resume</h2>
        <h3>Hide what you don't want others to see</h3>
        
    <canvas id = "myCanvas" style = "background:#FFF;" width = "800" height = "800"></canvas>
    </div>
</section><!--//promo-->

<script>
	var canvas = document.getElementById('myCanvas'),
  var context = canvas.getContext('2d');

  context.beginPath();
  context.moveTo(75,50);
  context.lineTo(125,50);
   context.lineTo(150, 93);
    context.lineTo(125, 136);
  context.stroke();


  make_base();

  function make_base()
  {
    base_image = new Image();
    base_image.onload = function(){
      context.drawImage(this, 100, 100);
    }
    base_image.src = 'https://resumebox-bucket.s3.amazonaws.com/resumes/resumes/000/000/049/fullsize/resume.jpg';
    //base_image.src = '<%=get_image_url(@resume.id, @resume.resume_file_name)%>';
  }

</script>

app/views/resumes/index.html.erb
<%= render 'layouts/navbar' %>

<section id = "resume" class = "resume section offset-header">
	<div class = "container text-center">
			<% @resumes.each do |r|%>
				<div class = "col-md-4 col-xs-12 col-lg-3" %>
					<td><%= image_tag r.resume.url(:fullsize) %></td>
					<p><%= r.user.name%></p>
				</div>
			<%end %>
	</div>
</section>

app/views/resumes/new.html.erb
<section id = "resume" class = "resume section offset-header">
	<div class = "container text-center">
		<% provide(:title, 'Add Resume') %>

		
		<h1>Add Resume</h1>
		<div class="row">
			<div class="col-md-4">
				<%= form_for(@resume) do |f| %> 
				<%= render 'shared/error_messages' %>
				<%= f.hidden_field :user_id, :value => current_user.id %> 
				<%= f.hidden_field :faculty, :value => current_user.faculty %>

				<%= f.label :company_list, "Which companies gave you interviews? (Separate using commas)" %>
				<%= f.text_field :company_list, class: "form-control", placeholder: "Ex. Google, Facebook" %>
				<div class="field">
				    <%= f.label :resume %><br>
				    <%= f.file_field :resume%>
				</div>
			
				<%= f.submit "Create resume", class: "btn btn-primary" %>
				<% end %>
				
		  	</div>
		</div>
	</div>
</section>

app/views/resumes/resumesarts.html.erb
<%= render 'layouts/navbar' %>

<section id = "resume" class = "resume section offset-header">
	<span><%= link_to "Arts", 'resumesarts' %>
		<%= link_to "Math", 'resumesmath' %>
		<%= link_to "Engineering", 'resumesengineering' %>
	</span>
		<p></p>
	<div class = "container text-center">

			<% @resumes.each do |r|%>
        <% if r.user.faculty == "arts" %>
				<div class = "col-md-4 col-xs-12 col-lg-3" %>
					<td><%= link_to image_tag(r.resume.url(:fullsize)), resume_path(r) %></td>
					<p><%= r.user.name%></p>
					<p><%= r.user.faculty%></p>
				</div>
        <%end%>
			<%end %>
	</div>
</section>

app/views/resumes/resumesengineering.html.erb
<%= render 'layouts/navbar' %>

<section id = "resume" class = "resume section offset-header">
	<span><%= link_to "Arts", 'resumesarts' %>
		<%= link_to "Math", 'resumesmath' %>
		<%= link_to "Engineering", 'resumesengineering' %>
	</span>
		<p></p>
	<div class = "container text-center">

			<% @resumes.each do |r|%>
        <% if r.user.faculty == "math" %>
				<div class = "col-md-4 col-xs-12 col-lg-3" %>
					<td><%= link_to image_tag(r.resume.url(:fullsize)), resume_path(r) %></td>
					<p><%= r.user.name%></p>
					<p><%= r.user.faculty%></p>
				</div>
        <%end%>
			<%end %>
	</div>
</section>

app/views/resumes/resumesmath.html.erb
<%= render 'layouts/navbar' %>

<section id = "resume" class = "resume section offset-header">
	<span><%= link_to "Arts", 'resumesarts' %>
		<%= link_to "Math", 'resumesmath' %>
		<%= link_to "Engineering", 'resumesengineering' %>
	</span>
		<p></p>
	<div class = "container text-center">

			<% @resumes.each do |r|%>
        <% if r.user.faculty == "math" %>
				<div class = "col-md-4 col-xs-12 col-lg-3" %>
					<td><%= link_to image_tag(r.resume.url(:fullsize)), resume_path(r) %></td>
					<p><%= r.user.name%></p>
					<p><%= r.user.faculty%></p>
				</div>
        <%end%>
			<%end %>
	</div>
</section>

app/views/resumes/show.html.erb
<%=render 'layouts/navbar'%>
<section id = "resume" class = "resume section offset-header">
	<div class = "container text-center">
		<h2><%= @resume.user.name %>'s resume</h2>
	<p><%=@resume.id%><p>
		<td><%= image_tag @resume.resume.url(:fullsize) %></td>
	</div>
</section>

app/views/shared/_error_messages.html.erb
<% if @resume.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@resume.errors.count, "error") %>.
    </div>
    <ul>
    <% @resume.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/staticpages/home.html.erb
<%= render 'layouts/navbar' %>
<!-- ******PROMO****** -->
<section id="promo" class="promo section offset-header">
    <div class="container text-center">
        <h2 class="title">Resume<span class="highlight">Box</span></h2>
        <p class="intro">Share and View Internship Resumes</p>
        <% if !user_signed_in? %>
            <div class="btns">
                <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-cta-primary" %>
                 <%= link_to "Login", new_user_session_path, class: "btn btn-cta-primary" %>
            </div>
        <% else %>
                <%= link_to "Logout", destroy_user_session_path, :method => :delete, class: "btn btn-cta-primary" %>
        <% end %>


        <ul class="meta list-inline">
            <li><a href="https://github.com/xuyuwei/resumebox" target="_blank">View on GitHub</a></li>
        </ul><!--//meta-->
    </div><!--//container-->
    <div class="social-media">
        <div class="social-media-inner container text-center">
            <ul class="list-inline">

            </ul>
        </div>
    </div>
</section><!--//promo-->
<!-- ******ABOUT****** -->
<section id="about" class="about section">
    <div class="container">
        <h2 class="title text-center">What is ResumeBox?</h2>
        <p class="intro text-center">ResumeBox is a platform where students are able to share their resumes and view other resumes in order to help with the internship/job hunting process. Most people post their resumes on their LinkedIn profile or personal website anyways, so we think of this website as an extension of those online profiles. Upload your resume today and begin viewing other people's resumes!</p>
    </div><!--//container-->
</section><!--//about-->

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<%= render 'layouts/navbar' %>
<section id="account" class="account section offset-header">
    <div class="account-container container text-center">
        <h2>My Account</h2>
        <br>
    </div><!--//container-->

    <div class = "container">
    	<h2>My Resumes</h2>
    	<% if @user.resumes.any? %>
    		<h4>(<%= @user.resumes.count %>) resumes. </h4>
        <% @user.resumes.each do |r|%>

        <li >
        	<span class="timestamp"> Posted <%= time_ago_in_words(r.created_at) %> ago. </span>
        	<%= link_to "delete", r, method: :delete %>
          <%= link_to "edit", edit_resume_path(r) %>
        </li>
        <% end %>
    	<% end %>
    </div>

    <div class = "container">
        <button> <%= link_to "Add a Resume", new_resume_path, :class => "btn btn-primary" %>, </button>
    </div>
</section><!--//promo-->